// ===========================================================================
//  FORESTER: RECKONING — Copyright (c) 2026 Roan Fraese / DeadlyDog Productions
// ===========================================================================

// WHAT HAS CHANGED — the update log on the front door, newest first. It is
// kept beside the code it describes, as the first Forester's is.

export const CHANGELOG = [
  {
    v: "0.41", date: "3 October 2026", title: "Tools and uniforms",
    items: [
      "Fixed: settlers' hands and skin stretched out with their arms. Everyone's arms are now their own, so a hand hanging against the hip no longer drags the hip, the coat or a pocket flap along when it reaches out.",
      "The watch wears a uniform, and you choose it: G, then Taxes & trade, then The watch's uniform. Pick the coat, the breeches, the waistcoat, a morion helmet with a sash or a tricorn with its colour. Everyone on the watch changes into it at once, and anyone set to the watch puts it on.",
      "Every settlement has its own yard: a chopping block to make tools at and a sawhorse to hew doors on, both using that settlement's own logs. Its stack, or its woodshed once it has one, takes logs in and gives them out. Each woodshed shows its own settlement's logs, and the first settlement's stack no longer wanders off to a woodshed built somewhere else.",
      "The government menu (G) is the government of the settlement you're standing in: its people, its families, its stores and its food. The treasury, research and laws are the nation's, the same from anywhere. Sending for someone picks the settlement you're in.",
      "All the tools rebuilt to match the rest of the forest: faceted, plainly shaped, each showing what it's made of. A pickaxe is a fire-hardened wooden point, two stone wedges lashed on, or a forged crescent of copper, bronze or iron. A hammer is a wooden mallet, a lashed stone or a forged head. The axe, the spade with its T-grip and treads, the sickle with its bright inner edge, the saw with its teeth and cut-through handle, the knife, the swords with their fullers and turned guards, the spear, the club and the battle-axe all have ground edges where they cut.",
      "Strike a rock with a pick and chips of it fly out, in its own colour, with a puff of grit, and lie a moment where they land. A pick too soft for the rock throws only a few, and breaking a rock throws plenty.",
      "Fixed: you couldn't get onto the stair to the loft. Its first step is now within reach, and anything standing in the stair's corner is moved out of the way.",
      "Township's description said settlers take their goods to the town hall on their own. They don't, and never did. It now says what it really does: it unlocks the town hall (a brick one is the charter you need to rebuild in the city style, and to be called a City) and the quarryman's trade.",
    ],
  },
  {
    v: "0.40.1", date: "3 October 2026", title: "Upstairs",
    items: [
      "Your house has an upstairs. A steep stair in the corner by the door climbs to a loft under the roof, with a bed and its red blanket, a chest, a stool by the window and a rail round the stairwell.",
      "The windows are real. Thirteen glazed, leaded windows, five downstairs and eight in the loft, and you can look out of every one, across the clearing and into the forest. The timbers inside step round them.",
      "Fixed: a beam ran across the doorway inside the rebuilt house. The rail now stops either side of the door.",
    ],
  },
  {
    v: "0.40", date: "3 October 2026", title: "Faces and families",
    items: [
      "Everyone has been rebuilt from the skin out. Faces are sculpted in one piece: a brow and eye sockets, cheekbones, a real nose, lips, a jaw and a chin, with colour in the cheeks and the eyebrows painted on. The eyes have an iris and pupil and a lid over them. Hands have fingers and a thumb. Hair is combed in strands from the crown to a clean hairline, and beards grow from the skin. Coats hang open in folds to the knee, split up the back, with pocket flaps and buttoned cuffs. Breeches are buckled at the knee, and shoes have heels and buckles. Skirts are gathered and full, with a darker hem, and aprons hang over them. Women wear a kerchief crossed at the breast and a linen coif with a frill. Tricorns have their brims pinned up properly. Shade gathers under brims and in folds and eye sockets.",
      "Raiders dress like the forest men they are: a shaggy mantle of skins over the shoulders, a leather jerkin and a ragged tunic, a rope belt, bare arms with leather bracers, legs bound in strips, furs round the ankles, a fur cap, wild hair and beards.",
      "Children grow up. A child grows over three years (24 days), getting taller and losing the big head of a little one. Then they're grown, and take up hauling: F beside them to set their work. And children are born: a family with a man and a woman, well fed and content, may have a child, a son or a daughter with a name of their own.",
      "A Families tab in the government (G). Every family, its people, and what it thinks of each of the other families, from close friends to out for blood. Click a family to see who each of them likes least and most, and every reason: a quarrel over a borrowed axe, taking a cousin's side, another creed, hard times, good times, a generous neighbour, time healing. Feuds are marked in red.",
      "Settlers quarrel less often and less bitterly, and old grudges soften a little every day unless a feud keeps them up. Good times, working side by side and sharing a faith win them round.",
      "Rebuild your cabin as a house and the outside changes too: a two-storey house in timber and plaster with a red tile roof, like the settlers' own, with your door and a chimney over your hearth, and a boarded ceiling inside.",
      "Crafting shows everything you can make with what's built. Recipes you're short of are greyed out, with what's missing in red. Copper, bronze and iron tools stay hidden until you have a forge, and it tells you how many more recipes a forge would open.",
      "A new felling axe: a bearded head forged thin to a bright honed edge, with a wedge in its eye and a cord whipped under it, on a curved oval hickory haft with a knob at the end.",
      "A stump goes when a tree grows back on it.",
      "Settlers earn money of their own. Once a day each takes a break to make something in their own time: kindling, a basket of mushrooms, a bunch of herbs, a rabbit skin, a whittled spoon or carved pegs. When Henning or Tobias is in, they take it to him and sell it for their own purse. None of it comes out of the settlement's stores, and none of it is taxed. The People tab shows what they have to sell and what they've saved.",
      "Thieves take goods as well as coin now: rye, loaves, meat, planks, stone, bricks or iron out of the stores. They hide it, and sell it on the quiet to the next trader. You may hear that someone was seen selling planks to Tobias, and wonder where they came by them. With a jail and a watchman, the watch may catch them in the act: the money goes back to the treasury and the thief to the jail.",
      "The name of what's in your hand shows for a moment right below its slot whenever you change it, with the wheel or 1-9. Hover over anything on the bar, in the inventory or in a chest, and its name shows right below it.",
      "Policing can be researched from the start (15 DM, in the Military Philosophy tree): the jail and the watch, to catch thieves, no longer wait on Trading, Currencies and Marketing.",
      "Fixed: a ripe field could still be reaped in the middle of winter. Nothing is reaped or sown till spring.",
      "Planks and bricks have pictures of their own: a stack of sawn boards and a pile of red bricks, instead of a door and a stone.",
    ],
  },
  {
    v: "0.35", date: "3 October 2026", title: "Rough edges",
    items: [
      "The charcoal burner's camp, mended. The turf on the clamp lies flat against it, overlapping like scales, instead of sticking out at all angles, and the vents are glowing holes in its side, not balls floating off it. His ladder is one ladder, rungs and rails together, leant up the clamp. The poles of his hut lean in and cross at the top. His fire is a real little fire with sticks burning in it and a kettle on a hook, not a flat orange disc. The charcoal sacks are coarse cloth tied at the neck, not wooden balls, and the baskets are wicker with charcoal heaped in them.",
      "Every settlement keeps its own people and its own stores. A new settlement starts with a cart's worth of logs and rye and nobody living in it: raise cabins there, then send for people to settle it (G, People: choose the trade and where they go). They live, work and eat there, from its own stores, and its store chest is its own. The treasury, the research and the laws stay the nation's, shared. The bar at the top shows the stores of whichever settlement you're standing in.",
      "Fixed: the Nation tab (G) showed nothing. It shows the food again, with how many mouths there are and what each eats in a day.",
      "A gunsmith: once your settlement reaches fifty souls, Matthias comes up the road from Suhl and sets up his bench. He makes muskets to order, a hundred DM each and a quarter of an hour of play apiece, one at a time. Order one for yourself out of your own purse and collect it at his bench, or order them for the settlement's armoury out of the treasury. Your musket: right mouse to raise it to your eye, click to fire (a loud bang, a cloud of smoke, and it hits hard: a raider anywhere, double in the head), then six slow seconds of loading. In a raid, the armoury's muskets go to the watch first: they fire from range, then club with the empty musket while they reload.",
      "Cut down bushes and ferns: swing the axe or a blade at one and it comes down in a scatter of leaves, and stays down.",
      "Look at a grave and its cross says who lies there, how they died, and on what day.",
      "Rye and rye seed have different pictures now: a sheaf for the rye, the seed corn for seed.",
      "The inventory (T) shows your tools: the axe, the pickaxe, the spade, the hammer, your own sword, your backpack, the bow and your arrows, each by its making, with what it does and a bar showing how worn it is (and how many strokes it has left). Hands shows what you're really holding: the blade, the pick, the bow or food.",
      "Snow lies on the ground, the trees, the roofs and the woodpiles, but not on people or on what they hold: no more snowy heads, shoulders, axes or hands.",
      "At a trader you choose who pays: the treasury or your own purse. From the treasury, what you buy goes to the stores and what you sell comes out of them, as before. From your purse, what you buy goes in your pack and what you sell comes out of it, and the money is yours. The settlement's own purchases (the saw, the woodcutters' axe heads, iron tools) are paid from the treasury. Rye and rye seed can be carried now, and put in the store chest.",
      "Eat straight out of your inventory (T): click any food on you to eat it. Blackberries and roast meat have their proper names there now.",
      "The bar at the bottom holds only what you carry. The settlement's bread is no longer on it: take bread from the store chest to eat it.",
      "Fighting is harder. A raider draws his blow back for a full second before it lands, and all that time a big red mark by the crosshair shows the side it's coming from: up for a blow from above, left or right for the sides. Raise your guard on that side (right mouse) just before it lands to parry; held up all along, it only blocks, and costs you breath. Your blows no longer stop his once he's started it, so you can't just hack away, and he moves his guard to the side you're on more often. Raiders are tougher (85 health) and hit harder.",
      "Raiders can be shot down: an arrow strikes anywhere on a man, feet to head, not only his middle, and an arrow in the head does double.",
      "Your brother or sister wants you to make a stone pickaxe before you go down into the cave, since a wooden one won't touch copper. The marker and the objective take you to the chopping block for it first: a wooden pick, the grey stone round the clearing broken with it, and then the stone pick. Then the cave.",
      "Fixed: you could pick blackberries in the snow. In The First Winter there's no settlement to say it's winter, so the brambles didn't know; now they go bare whenever snow is lying, as well as in the settlement's winter.",
      "In the free camera the mouse wheel sets its pace: roll it up to fly faster (up to twenty times as fast, for crossing the country) and down to creep (down to a quarter, for close work).",
      "The pickaxe only ever swings overhead, down into the rock, whichever way you've turned (and the arrow by the crosshair that shows the side of your next stroke stays away while you hold it). Seen from outside, you swing it overhead too.",
      "Fixed on Windows: crouching with Ctrl while walking forward closed the game, because Ctrl+W was the app's Close Window shortcut, and Ctrl+M minimised it. On Windows the menu has no Ctrl shortcuts now. F11 and Alt+F4 still work.",
      "The mouse wheel goes along the bar at the bottom: down for the next thing, up for the one before, round and round. It takes up tools, weapons, the bow and food, and passes over things you can't hold, like logs and arrows.",
      "The charcoal burner lives in a different hut: a ridge pole on crossed poles at each end, two bark-slab roofs coming down to the ground, gables of upright split logs with the doorway toward his fire, and sods along the eaves.",
      "Fixed: with food in your hand, being given the axe (or taking up a blade, the pickaxe or the bow) left the food in your hand and the axe hidden behind it, and a click took a bite instead of a swing. Taking up anything now puts the food away, and if the axe was already out behind it, pressing its number shows it again instead of putting it away.",
      "Fixed: when the watch came for Father, he could walk to you and keep on walking, and the scene never went on. Now a scene waits a few seconds at most for anyone walking into place, then carries on. The same goes for the Amtmann, Kessler and Jakob in the last chapters.",
      "Fullscreen in the settings: tick it for the whole screen, untick it for a window. It's remembered, and the game goes back to fullscreen at your first click next time. F11 still works too.",
      "Rye takes longer to come: a field stands a stage every two days, four days from sowing to ripe (Agriculture and weeding still bring it on sooner). A harvest gives sixty rye now, seventy-two with a well, so the fields still feed you.",
      "Fields snap against each other properly. A field snapped onto the first one you ever dug was always refused, because a circle kept clear round that field kept other fields away too. And a field is now checked as the rectangle it is, not a circle round its corners, so it can lie right up against its neighbours. Aim near a field and it goes on the nearest side where it really fits.",
      "If the graphics give out (some Windows graphics drivers drop them), the game saves what you have, starts again by itself and puts you straight back into your game, instead of freezing or closing. A small slip in the background no longer closes the app either: it's written in the log (Help → Show the error log) and the game carries on.",
      "Fixed for Windows: the app wouldn't open at all, because its data folder had a colon in its name, which Windows doesn't allow. If anything ever stops it starting now, it says so in a box instead of quietly closing.",
      "The bow, made real. The draw comes easily at first and harder the further back it comes, and the limbs creak as you pull. Held, the aim wanders, a little more the longer and harder you hold, and the arrow goes where the bow was really pointing. Hold Shift at full draw to hold your breath and steady it for a few seconds; it costs wind, and you shake worse after. The string goes with a deep twang and a slap. The bow kicks forward and rolls in your hand, the string shivers, your drawing hand flies back past your ear, and the view jolts. Then your hand goes back over your shoulder to the quiver and brings the next arrow to the string. A part draw let go is let down gently, not shot. You walk slowly with a bow drawn, and can't run. Arrows flex and wobble just off the string, and straighten as they fly.",
      "Food goes in your hand now: press its number to take it out, click to take a bite, and press the number again to put it away. It stays in your hand while there's more of it.",
      "Fixed: heads that wound round and round, or ended up looking over their own shoulders. Your sister, and anyone else turning to look at you, now turns her head only as far as a neck goes.",
      "Fixed: rebuilding the cabin in The Clearing didn't take its twenty logs off the stack.",
      "The charcoal burner's clamp is one turfed mound now, lumpy and patched green and brown, with its foot following the ground. Its glowing vents are set into its side, and his ladder leans against it.",
      "New animations for everyone in the game. In a fight, people stand in a real guard, weapon or fists up and the weight rocking, and step sideways round each other instead of walking forward while sliding sideways. Blows come from the side or straight down from overhead, with the wind-up showing before the blow lands. Anyone hit flinches: the head snaps back and the body twists away.",
      "Anyone knocked down goes over backwards instead of snapping flat, and gets up the same way.",
      "Settlers carrying logs, sheaves or sacks keep their arms round the load while they walk. Farmers dig with the spade driven in by the foot, reap stooped with the sickle swept low, and sow with the seed cast wide in an arc. Grubbing out stumps is spade work too.",
      "In first person, reaping has its own stroke now: a sickle swept low through the stalks. Picking berries, pulling an arrow out, gathering moss or picking up a stone shows your hand reaching out, closing round it and pulling back. Each piece of work in a field sounds like itself: the spade's bite, the sickle's swish, the seed falling.",
      "Fixed: restarting a chapter (or going back to the title) while in the free camera left the HUD hidden. Starting any chapter now always puts you back in yourself. While the free camera is on, a banner says so, and ; brings you back even with a menu open.",
    ],
  },
  {
    v: "0.33", date: "2 October 2026", title: "Duels and daily bread",
    items: [
      "Fights are one-on-one. A raider who comes at you squares up to you alone: he stops to fight instead of making for the stores, circles you, steps back out of reach and closes again, and doesn't let go until one of you is down. Hit another one and he turns on you, and the first lets you be.",
      "Settlers pair off with raiders, one each, and fight it out the same way, circling and stepping back out of a wind-up. Anyone without a raider to pair with waits a few steps off, ready to step in when one falls. Rebels in a rising, and the bandits in the cave, fight the same way.",
      "Farmers carry the reaped rye to the store chest in sheaves, and the baker fetches it from there in a sack and carries it to the oven.",
      "Food by the day: each settler (and your brother or sister) eats five rye, or three loaves, or two meat a day. Your kitchen's dishes are a whole day's food, and come first, then bread, then meat, then rye. A field now gives forty rye (forty-eight with a well), and a baking turns four rye into six loaves, so bread goes more than twice as far. Henning sells rye by the twenty-five, and his salt pork is twelve meat.",
      "Harvest Home puts food first: your brother or sister explains what everyone eats in a day and what the days' food on the board means, and the chapter asks you to reap the rye, put someone in the fields as a farmer, and lay in five days' food before the rest. The chapter opens with three days' food in the stores and 10 DM in the chest, whatever state the summer left you in.",
      "Tobias the pedlar sells food: a sack of 25 rye, 15 loaves of Lübeck bread, and smoked herring (ten meat). He still has his salt pork and rye seed.",
      "The settlement bar shows your rye seed, the meat in the stores, and how many days the food will last everyone, in red when it's under two.",
      "Fields snap together: a new field near one already dug sets itself edge to edge and square with it, so the fields make one patchwork.",
      "Rye seed: sowing a new field takes a seed, and every harvest gives back a third of one. You start with three, and Henning sells them for 3 DM.",
      "Tools wear out. Every stroke wears a tool, and better makings last longer: wooden 60 strokes, stone 120, copper 200, bronze 300 and iron 450. A bar under each tool in the hotbar shows what's left, and turns red when it's nearly gone. A worn-out axe or spade leaves you the old one from the block; anything else has to be made again.",
      "In build mode, Y turns what you're placing the other way (R still turns it, and Shift+R still reverses it).",
      "Fixed: once you had a woodshed, the old log stack by the cabin was gone, but it still stood there invisibly, blocking the way and showing on the map. Now it goes with it.",
      "With no farmer in the settlement, the fields aren't left to rot: whoever stands in for the farmer (the hauler, or anyone grown) reaps and sows them too. Hunters bring home four meat from a kill instead of two.",
      "Settlers dig new fields now. A field you stake out used to sit there until you dug all three strips yourself; now the farmer turns it over a strip at a time with the spade and sows it. With no farmer, the hauler does it, or anyone grown. You can still dig it yourself (hold F).",
      "The map shows your settlement as it stands: every building in its real shape and turn, sites still being built as dashed outlines, paths as tracks, and fields coloured bare, growing or ripe.",
    ],
  },
  {
    v: "0.32", date: "2 October 2026", title: "In your hands",
    items: [
      "First-person hands that move with you. Whatever you hold sways behind you as you turn and catches up, bobs in a figure of eight with your stride, and rides lower and tilted when you sprint. It drops as you land from a jump and floats as you fall, rolls as you step sideways, and rises and falls with your breath when you stand still.",
      "Taking something out (the axe, a blade, the bow, a tool for a job) brings it up into view from below instead of popping it into your hands.",
      "Strokes land with weight: the view turns with the swing, and when the blade bites (a tree, a rock, a raider) the stroke checks for a moment and the jolt runs up your arms.",
    ],
  },
  {
    v: "0.31", date: "1 October 2026", title: "The kitchen",
    items: [
      "The app updates itself now: when a new version of the game is out, it downloads in the background and asks whether to restart into it. There's no need to install the app again. Help → Check for updates looks straight away.",
      "Better animation all round. People walk and run with knees that fold as the leg comes through, feet that push off and lift, hips and shoulders turning against each other and the head held level. Standing, they breathe and shift their weight, and glance about. Felling has a real wind-up, a fast stroke and a follow-through, and hammering lifts slowly and comes down hard. Every held pose breathes instead of standing frozen.",
      "Deer and boar rock as they gallop, nod their heads as they walk, and look up from grazing to glance about. Shot running, they carry on a stride or two before going down, legs kicking.",
      "Landing from a jump or a drop: the view dips as your knees take it, harder the further you fell, with a thud underfoot.",
      "The cave is where a fork in the road runs out now: the track that used to stop at a fallen spruce goes on to the cave mouth.",
      "A couple of days into free play, your sister tells you about the cave and asks you to dig ore there to sell to Henning and Tobias. Until you have a forge, she warns you can't use it yourselves: neither of you knows how to forge yet. It's marked until you get there.",
      "Better animation: the axe swing has a proper wind-up, a jolt on the wood and a follow-through; fist fights are fought with fists up in a guard, jabs and crosses; people eat with a spoon at the eatery's tables, the cook stirs the pot, and anyone you talk to turns and talks with their hands. People standing about turn their heads to look at you as you pass close. Deer and boar nod as they walk and rock as they gallop.",
      "Cinematic shading (Settings, on unless you choose Performance): shadows are softer shade instead of black, the darkest corners are lifted a little and cooled, light is warmed, fires and lit windows glow softly, and the picture has a gentle vignette and a fine film grain.",
      "A key to the map: press K for it beside the minimap, and it's always in the corner of the big map (J).",
      "Ore and caves are drawn properly on the map now: a lump of rock with copper's green flecks, tin's pale crystals or iron's rust streaks, and a cave as a hillside with its timbered mouth.",
      "Step into a tree and its branches thin away around you, so you can see out through them while you stand hidden in among them.",
      "The mouse lock in the app: the game waits longer for the lock, asks for it again at your next click, and the moment it comes, turning no longer stops at the edge of the screen.",
      "The charcoal burner's camp, rebuilt: a proper beehive clamp under its turf with the fire glowing through its vents, a ladder up it and a wattle windbreak, the next clamp half stacked, a cone hut of poles and bark, his fire with a kettle on a crane, heaps and baskets and sacks of charcoal, and soot trodden into the ground. The smoke drifts up soft now.",
      "A miss that lands near game sends it bolting away from where the arrow came from.",
      "An arrow that strikes a beast is spent: it breaks, and doesn't come back to the quiver. You can still pull your misses out of the ground.",
      "Blackberry brambles round the clearing and along the road: hold F to pick a handful. They fruit again a few days later, and stand bare in the winter.",
      "Jumping costs breath. Winded, you can't jump at all, and when you're nearly spent it's only a hop.",
      "Every tree gives two logs. A good saw, and Sawing and Sawmills, now make felling quicker instead of giving extra logs.",
      "The waypoint marker holds steady: one route to each objective, kept unless it really changes, and it glides across the screen instead of jumping between spots.",
      "Credits, on the main menu.",
      "The road no longer looks like wooden planks: its brown was being mistaken for timber and given wood grain. It has the plain earthy grain of the ground now.",
      "The roads melt into the ground now: their edges fade out over a wider band, and the grass along them and up the middle takes the colour of the ground there (litter, moss, dry grass, stone) instead of one green everywhere. The roads to new settlements fade in the same way.",
      "Two new settings: Saturation (from washed out to vivid) and Pixelation (from off up to 8×, for big hard pixels).",
      "Everyone's shoulders are joined on properly now: a broad shoulder line across the top of the chest that the arms grow out of, instead of arms hanging off a narrow neck. The arms hang closer to the body too.",
      "The kitchen stays locked until you rebuild your cabin as a house (B, inside the cabin). Until then there's only the fire.",
      "A kitchen in your house: rebuild your cabin in timber and plaster, and there's a brick range beside the hearth with a pot and a pan on it, a work table with a board and a knife, crocks on a shelf and herbs drying. F at the range opens the recipes.",
      "Cooking, properly: the meat is cut up on the board, then into the pan or the pot. Watch the gauge and take it off the heat (Space) in the green. Too soon and it's underdone or raw; too late and it's dry, or burnt black. Turn what's in the pan once, about halfway (F); keep the pot stirred (F) or it catches on the bottom.",
      "Eight dishes, from roast venison and fried hare to venison stew, boar with blackberries and wild boar stew. Some want rye or bread from the stores, or blackberries.",
      "Every dish is judged when it's plated: stars out of five, and the reasons. Good meat badly overcooked might be two stars, and the card tells you why.",
      "A meat for every beast: venison from the deer (rich, but dries fast), hare (delicate, quick to ruin) and boar (fat and filling; it must be cooked through). Each has its own taste, tenderness and filling.",
      "Wild boar in the woods: heavy, hard to bring down, worth two hides. Wound one when you're close and it comes for you.",
      "A Cooking skill (P): a truer eye for when a dish is done, a wider moment to take it off, better dishes, and new recipes as it rises.",
      "Tobias the pedlar buys your dishes. He tastes each one and decides what he'll pay.",
      "Put dishes in the store chest and your people eat them, the best first. Settlers who eat well are happier, and a bad meal sours their day.",
      "Eateries: a settler may open one instead of a shop, with tables and benches outside and a pot on a tripod. The owner buys meat and bread from the other businesses, or goes hunting and fetches rye, then cooks. The meals are as good as the cook. At midday settlers go and eat there, sitting down at the tables. You can buy a meal too.",
      "Families and feuds, as in the first Forester: everyone has a family name, and some newcomers are kin. People form views of each other. Let one sour far enough and the two families take up a feud and come to blows on sight; sometimes someone dies. The watch can lock up whoever starts it, or you can pay blood money to end it (F by anyone in it). Left alone, it burns out.",
      "New sounds: the sizzle and spit of a pan, a pot bubbling, the knife on the board, a spoon round the pot, a pan tossed, a plate set down, fists landing. New hand animations: stirring with a ladle, and turning with a spatula.",
    ],
  },
  {
    v: "0.30", date: "30 September 2026", title: "A country of its own",
    items: [
      "Settlers can die now, and not only in raids: a fever left untreated, days on end with nothing to eat or no wood for the hearth, the fighting in a rising, or the dark in the caves. The weakest go first. Each is buried by the graves, and the settlement mourns.",
      "A raider's victim no longer gets up and goes back to work once the raid is over.",
      "Dark Fantasy (Settings): a darker, colder, greyer world with the mist in close, drawn at low resolution in big hard pixels.",
      "Hares hop now, instead of walking like little deer: a bound, a pause, and another bound, long low leaps when they bolt.",
      "Caves: a mouth in a hillside out in the forest, and behind it hall after hall of dark rock, thick with copper, tin and iron. Your lantern and a few old torches light the way. Sometimes raiders have made their camp down there.",
      "A second settlement: after forty minutes of play you're asked whether to found one. Say yes and a road is cut through the forest to a new clearing, with its name on a signpost.",
      "Settlers earn wages selling their wares to the pedlar, and you tax them (G, Taxes & trade). A tenth of every tax is yours. High taxes make them unhappy, though the contented mind less.",
      "Companies: a settler who has saved enough may start one (Bread, Meats, Lumber, Stone, Ironmongers or Goods). Each has its own name, colours, pattern, emblem and banner. They fell their own timber and build a shop, and you can buy there cheaply. There's a business tax, and laws: forbid businesses, or make them ask your leave and show you the spot.",
      "A rising: keep the settlement miserable (under 35) and, after twenty minutes of play, the unhappiest take up arms with red rags on their arms. The loyal fight them in the streets. Lose, and they take the treasury and strike down the taxes.",
      "Horses: research Horses, build a Stable, and ride at more than twice walking speed. X gets you down.",
      "A backpack: prey drop hides, and four make a Hide backpack at the chopping block. Your pack holds 6 slots to start, 12 with the backpack, then 18 and 27 as you stitch better ones.",
      "Hunters: a new trade. They go out to the deer ride and bring back meat and hides.",
      "A cabin rebuilt in timber and plaster is a House, and sleeps 3. Your own cabin can be rebuilt as one too (B, inside), with plastered walls, a boarded floor and room for settlers in the spare beds.",
      "Claim new ground by drawing: hold the left button on the map and draw out from the settlement's edge round the ground you want, and back.",
      "The land rolls: hills, ridges and hollows. Paths and fields lie along the slope, and buildings are dug into it.",
      "Stumps can be dug up (hold F), and nothing grows there again.",
      "A building on a slope has its ground dug out for it: a level pad cut into the hill, with a bank of bare earth round it.",
      "Watchmen can be asked to follow you (F beside one, Follow me). They go wherever you go, down into the caves too, and fight at your side.",
      "Once you've found the cave, it's on your map. Inside, the map (J) and minimap show the halls you've been in, and the ore in them.",
      "Ten stones in the alley by the marsh gate now, along its whole length, instead of three.",
      "Fixed: what people held (axes, torches, lanterns, spades) wasn't in their hands at all, but hung beside them. It's gripped in the fist now.",
      "In first person your own body is there: look down and you see your chest, your coat and your other arm, joined up with the arm that holds your axe.",
      "Fixed: the ore in the caves was invisible. Fixed: coming back from the free camera left you crouched and slow.",
      "Paths are a quarter quicker to walk on. Settlers no longer clip through walls.",
      "Harder raiders: tougher, quicker, harder-hitting, more of them, and a parry stuns them for less time. Once Policing is known, only the watch fights them; everyone else takes cover.",
      "Everything yields less: fields give 4 rye (5 with a well), a loaf takes 2.5 rye, trees give fewer logs, and works and ore rocks make less. Food fills you less.",
      "No reaping or sowing in winter, and nobody tells you to. Your sibling only worries about food when the bread is short too.",
      "Logs from a tree felled far out stay where it fell, and haulers gather up logs left lying about, and dig out the stumps left in the settlement when they've nothing to carry. You still stack the woodshed yourself.",
      "Research advice names the whole path (\"Research Land Ownership, then Township, for a town hall\"), so it can always be done.",
      "; flies a free camera, with no HUD. Right-click is no longer a second F.",
      "Your breathing is softer, like breath and not like grass.",
      "Trees keep their own shape when you start felling them (no more turning into a fir the moment you swing), and every tree falls its own way: taller ones slower, birches quicker, with a twist, a roll and a bounce as it lands.",
      "Trees don't grow back where you've built: not through paths, fields, walls, shops or roads. Stumps under anything you lay out are grubbed up with it.",
    ],
  },
  {
    v: "0.29", date: "30 September 2026", title: "More room for logs",
    items: [
      "Woodsheds can be made bigger. Look at one (V) and build on a second bay (holds 70 logs), then a third (120). Each bay is the shed again, built on beside it, and the logs fill all of them.",
      "You can walk all around the quarry, and into its pit. Only the rock face round the back and the crane's post are solid.",
    ],
  },
  {
    v: "0.28", date: "30 September 2026", title: "Room to grow",
    items: [
      "Fixed: F (and Space, Enter and Escape) stopped working after the first guide card. It works again.",
      "You choose where the settlement grows. At 8 people, then 13, 19, 26 and 34, you earn a claim. Open the map (J), click Mark out new ground, and drag a line through the trees beyond the edge. The ground between your line and the settlement is yours to clear and build on. The map shades it green if it will do, red if not and why, and counts the trees on it. A claim can't be too big: 10 to 45 paces of line, and 1000 square paces at most.",
      "The settlement no longer grows by itself in rings. Everyone but the farmers fells the trees on new ground, and the road is always left open for newcomers.",
      "The map is fast: the forest, roads and fog are drawn once and only the piece in view is copied out, so the minimap no longer stutters as you walk, and the big map drags and zooms smoothly.",
    ],
  },
  {
    v: "0.27", date: "30 September 2026", title: "The guide",
    items: [
      "A guide: the first time you meet each part of the game (building, stone, tools, the forge, the stores, settlers, fields, research, trade, hunger, wounds, skills, winter, raiders), the world stops and a page explains how it works, step by step. H opens the guide book to read any of them again.",
      "Stone, ore and metal in your own pack count towards a building, a repair or a rebuild. You no longer need to put them in the stores first.",
      "Path strips snap together end to end. Nearly in line, they run straight on. At an angle, they meet in a clean corner with rounded ends and no gap.",
      "A quarry can be staffed as soon as it stands. The quarryman's work no longer waits on Township. Any work building you can build, you can put someone to.",
      "Only haulers carry logs and stone to building sites, and the game now says so. A site tells you when nobody is hauling.",
      "The settlement's stores are kept outside now, in a store chest under a little roof, built as one of the summer's tasks. The chest in your cabin is yours: what you put in it you can sell, and that DM goes into your own purse. Arrows cost 4 DM a dozen, from your purse.",
      "Your sibling asks you to raise a cabin for Tomas and Grete.",
      "Farmers really farm: they reap, sow and weed the strips, and you can reap and sow by hand beside them.",
      "B puts the plans away. Buildings turn smoothly while R is held, with no snapping. Paths are low-poly strips of trodden earth.",
      "It's much easier to walk around cabins and buildings. The charred beams are gone from the cabin.",
      "The map of Europe shows your settlement by the name you gave it.",
    ],
  },
  {
    v: "0.26", date: "30 September 2026", title: "What it costs",
    items: [
      "Dying costs you now: whatever killed you — a raider, the plague, hunger — you wake in your bed with every skill a sixth down (15% of all your skill points). Hunger can kill, in the end.",
      "Settlers can die in a raid. The dead are buried in a row of crosses at the edge of the clearing, and everyone mourns for three days.",
      "Cook your meat: hold F at the fire. Eat it raw and you take the plague — the health bar goes green, nothing mends, and it can kill you. A hospital cures it.",
      "Skills are much harder to raise: the first levels come in an afternoon, the last take a lifetime.",
      "Ambitions, in G: eight long aims for the settlement — a village, walls, an age of iron, a market town, brick, standing against a crown — each with a reward. The last is Father's name, written back into the rolls in Hamburg.",
      "The settlers work the metals too: miners bring up copper and tin as well as iron, the smelter smelts them, and the smith casts bronze. Your own tools can take what they need from the stores.",
      "Everything in the stores is to hand from the chest in your cabin: take five at a click, and shift-click to put things in.",
      "Research gates what you can build in every chapter, not only in free play — and what isn't known yet isn't shown at all.",
      "Walls are laid out as sites now: stakes and a line, logs carried to them, then raised. The plans show the building itself as you place it, not lines on the ground.",
      "Rebuilding is offered only when you inspect a building (V). Paths can be laid from the start. F closes any menu. Tab shows every key.",
      "The menus are set like a book of the age: laid paper, a double rule in ink, fleurons at the corners, rubric red.",
      "A digging animation, and one for sowing. The swing mark is a short, pale bracket. A better pickaxe. The sister holds her axe level, and the settlers turn their blades into the trunk.",
      "The deer ride is restocked through the day. The log stack sits on the bare ground.",
      "Much quicker: the forest is drawn in tiles, with plainer trees in the distance and none past the haze — about six times faster on the same machine. The minimap slides smoothly under you.",
      "Your saves are safer: the app puts a copy by before every update (Help, Show save backups), keeps a log of errors, and a save that can't be read falls back on its last good copy.",
    ],
  },
  {
    v: "0.25", date: "29 September 2026", title: "Flesh and iron",
    items: [
      "Hunger: a bar under your health, below the map, and both always in sight. Eat by pressing the number of what you carry — bread from the store, meat, berries — and you raise it to your mouth and chew. Go too long without and your breath won't come back and your wounds won't close.",
      "Skills, on P: Strength, Toughness, Healing, Endurance and Archery, each from 1 to 100, and each grows by doing it. The tougher you are, the less a blow takes from you and the less it rattles you.",
      "A blow now lands: a red flash, a hard jolt of the view, and then you gasp for breath a while, the view trembling with it. Your breathing is louder and clearer.",
      "Tools: make a wooden pickaxe at the chopping block from two logs, and break the grey rocks round the clearing for stone. Stone makes a stone pick, which breaks the green copper rock out west; smelt the ore at a forge, cast copper and tin into bronze there, make a bronze pick, and go after the red iron rock deep in the woods. Copper and iron axes fell quicker. Your brother or sister shows you how.",
      "More to make at the block: copper and iron spades dig the fields quicker; a mallet, then stone, copper and iron hammers raise buildings and hew doors quicker; and a sword of your own — wooden, copper, iron — for when they come up the road.",
      "Every new cabin wants a door hewn for it at the sawhorse, as the first one did.",
      "A chest in the cabin: nine places to keep things. After the hunt, and after the sowing, you're asked to put the meat and the seed away in it.",
      "When Henning hands you the bow, the game stops and a picture shows how to shoot.",
      "An arrow by the crosshair shows which way your next stroke will come: left, right or overhead.",
      "The hunt wants three beasts brought down, not one.",
      "Guards see further, and when they catch a glimpse of something they come over to look. The watchman at the marsh gate keeps his post.",
      "When someone comes up the road, the people about turn to watch them come.",
      "Rebuilding in timber, brick or stucco costs a great deal of what it's built of, and no money.",
      "The forest floor is low-poly now, like everything else: needle litter, moss, bracken, dry grass, bare earth and stone on the banks. Things only take a grain — wood, stone — where it fits; cloth and paint keep their own colour.",
      "Nothing in the game speaks of the clearing before you reach it. The old axe stays yours once you take it. The charred beam is gone.",
      "The minimap draws five times quicker. There's a Quit button on the front screen of the app.",
      "Fixed: you could end up boxed in with no way out. Now you step out to the nearest clear ground.",
      "Bronze, as the first Forester has it: break the pale tin rock south-west of the clearing with a stone pick, smelt it at a forge, and cast one copper with one tin there for two bronze. Every tool and the sword have a bronze making between copper and iron — and the iron rock now wants a bronze pick.",
      "Your own sword and axe show their making: a wooden blade, copper, bronze, iron.",
      "Fixed: grass showed between the cabin's floorboards.",
    ],
  },
  {
    v: "0.24", date: "29 September 2026", title: "Closer",
    items: [
      "The map of Europe zooms: scroll, or the + and −, and drag to move about. The cities' names keep their size as you come in, so more of the towns find room.",
      "Zoom far enough and the parchment gives way to the land itself, in three dimensions: the true coasts, the mountains where the ranges run — the Alps, Pyrenees, Carpathians, the Scandinavian fells, the Apennines, the Balkans, the Atlas, the Caucasus, the Anatolian plateau — and the country as it grows: tundra in the far north, taiga and pine through Scandinavia and Muscovy, oak and beech woods among the fields of the middle, olive and cypress round the Mediterranean, grass steppe on the Pontic and Hungarian plains, desert beyond the Atlas, rock and snow on the heights. Come right down and the woods are trees.",
      "The cities stand on it — houses and a church, named, in their masters' colours — and the borders are drawn on the ground. Click a city or a stretch of country there as on the map. Scroll out again and you're back on the parchment, where you were.",
      "Click a city on the map to see who holds it — and who held it in 1683, if it has changed hands. The crowns are named in English on the map now; the seas and the title keep their Latin.",
    ],
  },
  {
    v: "0.23", date: "29 September 2026", title: "A map of 1683",
    items: [
      "Europe (G) is the real Europe now: the true coasts, and each piece of land given to the crown that held it in 1683 — Denmark with Norway and Holstein, Sweden round the Baltic from Finland to Pomerania, the Spanish Netherlands, Royal Hungary and the Ottoman rest, Podolia lost to the Turk, the Cossacks on the Dnieper. The Dutch Republic and Morocco join the crowns.",
      "And it is drawn as a map of the time was drawn: engraved in sepia on old paper, the coasts water-lined, each crown coloured by hand along its borders, hills in profile, rivers, the great towns, the names in Latin — GALLIA, SUECIA, MOSCOVIA, OCEANUS GERMANICUS — a compass rose with its rhumb lines, a ship, a sea serpent, a cartouche, a scale of German miles, and the degrees round the frame counted from Ferro.",
      "Cities on the map: a hundred of them under their names of 1683 — Wien, Kiøbenhavn, Constantinopolis, Danzig, Chyhyryn — each a dot, the crowns' seats ringed in the colour of whoever holds them. Click a crown to see its cities.",
      "Wars between the crowns take a province at a time, and the borders visibly move; a city in a province taken changes hands, and word comes of it — \"The Austrian Empire takes München and Augsburg from Bavaria!\" A saved game's old conquests, drawn on the old map, are cleared.",
      "The borders of 1683 put right: Stettin Swedish, Silesia the Habsburgs', Pomerania and Ducal Prussia Brandenburg's, Leipzig and Dresden Saxony's.",
    ],
  },
  {
    v: "0.22", date: "29 September 2026", title: "The sick, and the hospital",
    items: [
      "Settlers fall ill now and then — more often when a crown near you has the plague, in a cold winter, or if they're sickly; less if they're hardy, or there's a well. A sick settler keeps to their bed and can't work, and feels it (−10).",
      "The Hospital (Physick): with a doctor at work in it — a new trade, and Physicking the skill of it — the ill are up in a day or two instead of most of a week.",
    ],
  },
  {
    v: "0.21", date: "29 September 2026", title: "Walls, and Europe",
    items: [
      "Europe, in G: the first Forester's map of 1683 — thirty-three crowns, their coastlines inked — with your home in the woods beyond Hamburg. It lives: the crowns go to war with each other and the borders move, plague and famine fall on them, and word of it reaches you on a card.",
      "Each crown has a view of you, set by its faith and yours. Send an envoy to warm it; once it's friendly, a trade pact brings a DM a day in customs. The crowns near enough to march — Denmark, Sweden, Brandenburg, the Empire, Saxony, Poland, England, France, Bavaria — can be at war with you: declare it, or have it declared on you if they come to hate you.",
      "At war, it isn't bandits that come up your road but a crown's soldiers — more of them, with swords, in its colours, every few days. Beat them at your gate twice and it sues for peace and pays for it; or buy peace yourself.",
      "Walls, as the first Forester's Defending gives them: a palisade of sharpened logs, laid a length at a time (three logs each) — each new length joins on where the last one ends — and gates in it. With Defending II, stone walls.",
      "Gates stand open, and are shut when raiders come. Raiders can't walk through a wall: they hack at it, and a length that's taken enough is broken through — rubble, and a way in. Look at it and press V to mend it.",
      "Fixed: the settlement's buildings could be walked straight through — by you, the settlers and the raiders. So could the burned cabin's walls, the fire, the log stack, the chopping block and the furniture in the cabin.",
    ],
  },
  {
    v: "0.20", date: "29 September 2026", title: "Faith and law",
    items: [
      "The seven faiths of 1683, as the first Forester has them, in the proportions they walked out of a North German wood: Lutheran, Catholic, Reformed, Mennonite, Jewish, Orthodox, Muslim. Each settler holds one, and it shows: Catholics keep the holy days and give alms, the Reformed work harder, Mennonites won't take up a weapon, a Jewish settler arrives with capital, the Orthodox fast.",
      "A state creed, proclaimed in G, Faith & law: its own are glad of it, everyone else resents a state church not their own. Under it, with its church standing, dissenters may slowly come over — some never do.",
      "A church or a shrine is raised to one faith: the state creed, or the biggest congregation. A new building, the Shrine (Consecration): somewhere of their own to pray. Having nowhere weighs on a village; being the only one of a faith weighs on a person.",
      "The law: a miserable settler may take from the stores in the night (never a Lutheran or a Mennonite). A new building, the Jail (Policing): with a watchman on the job the thief is caught, what they took comes back, and they're held a day and disgraced.",
      "The Edict of Expulsion: every dissenter from the state creed out on the road at once. It asks twice.",
      "Faith shows in the People tab too, beside temperament and mark.",
    ],
  },
  {
    v: "0.19", date: "29 September 2026", title: "People, as the first Forester has them",
    items: [
      "Skills: every settler has the first Forester's eleven — Woodcutting, Quarrying, Farming, Building, Smithing, Crafting, Fighting and the rest — from 1 to 100. They come knowing their trade a little, and learn by doing it: a master works in a little under half the time, and a master working nearby teaches faster.",
      "Training: pay out of the treasury to raise someone a level in the skill of their work (G, People).",
      "Temperaments, one each for life, from the first Forester's six pairs: industrious or idle, hot- or even-tempered, gregarious or solitary, stout-hearted or timid, generous or grasping, hardy or sickly. Each bends their work, their fighting, their mood or how the winter takes them.",
      "Marks, for what happened to them here: hardened for standing up to raiders, bitter for being beaten down and left lying, contented after a long run of good days.",
      "A mood of their own: the settlement's contentment, and then their own — temperament, mark, a bed of their own, work they're good at. Two miserable days and they go back down the road; you're warned the day before.",
      "Send for someone: pick a trade in G, People, pay 12 DM, and if there's a bed free they come up the road with the trade already in their hands.",
      "The People tab shows it all: temperament and mark, a mood bar (hover for why), what each is best at. Click a name for their whole sheet.",
    ],
  },
  {
    v: "0.18", date: "28 September 2026", title: "Look closer, and learn to build",
    items: [
      "Six saves, as in the first Forester: Saves on the title screen shows each one — who, how far, the settlement and its day, when you last played — to continue, start over, delete, or export to a file and import back (into any save, or on another computer). New Game asks which save to use. The game you had already is save 1.",
      "Fixed: a settlement with buildings in it could freeze the game solid a moment after starting — every building kept putting itself up again, over and over.",
      "V: look at a building and press V to see it up close — what it's for, who works there, what it costs to keep — and rebuild it in the next style or pull it down, for half its logs and stone back (three quarters, knowing Ownership). An unfinished site gives back all it was given.",
      "Upkeep, as in the first Forester but lighter: every work that must be tended — the well, the bakery, the forge, the market, the quarry, mine, sawmill, smelter, brickworks, the town hall and the church — costs half a DM a day. Cabins, fields, paths and the woodshed cost nothing. Short of it, the works stand idle until it's paid.",
      "More is learned than given: the woodshed wants Tree Cutting, the well Replanting and the brickworks Masonry. A new settlement starts with cabins, fields and paths.",
      "The settlement has its sounds again: felling, building and hauling had been silent. Settlers' work is only heard near them.",
    ],
  },
  {
    v: "0.17", date: "28 September 2026", title: "From above, from the left, from the right",
    items: [
      "Fixed: starting a chapter after playing one in the woods could leave the screen black.",
      "Strokes and guards have a direction. Look even slightly up and you strike from above; turn your view left or right and you swing from that side. Your guard goes the same way.",
      "Round the crosshair in a fight: a white mark for your side, a red one flashing where a raider's blow is about to come from, and a grey bracket on the side the raider in front of you is guarding.",
      "Parry by having your guard on his side as he swings — raise it, or move it there, just in time. A guard on the wrong side catches nothing. Strike where he isn't guarding, or he turns it aside.",
      "Raids are loud: war cries up the road, yelling and screaming through the settlement, a cry for every blow — and a ringing clang when steel meets steel.",
      "Out of breath, you hear yourself breathing, faster and harder the more spent you are.",
      "Fixed: on the first day the board told you to set someone to farming when there was nobody to ask.",
    ],
  },
  {
    v: "0.16", date: "28 September 2026", title: "Blades, guards and a health bar",
    items: [
      "Health: a bar of its own above your breath — ten red segments and a heart, with a pale trail showing what the last blow took. It mends slowly once nothing has hit you for a while. Run out and you go down, and come to by the fire with the raiders gone and some of the stores with them.",
      "Raiders come armed — knives, clubs, axes, now and then a sword — and carrying torches against the dusk.",
      "Parry: hold right-click with the axe or a weapon out to raise your guard. Raise it just as a raider swings and you turn the blow aside and leave him off balance; hold it up all along and you block most of it, at the cost of breath. Raiders and settlers parry too.",
      "Every grown settler fights: with a sword or a spear if the smith has made them, an axe if they fell trees, and their fists if not. Children hide by the fire. A settler beaten down gets up again when it's over.",
      "Swords, as in the first Forester's tree: once the settlement knows Spears, Swords or Battle Axes, the smith forges them, turn and turn about with tools, until there's one for every pair of hands. Hilts make them cheaper, Blades makes them bite harder. Take the best one from the hotbar.",
      "Your brother or sister gives you a hint when you've been at one thing a good while, and speaks up when you're hurt, out of arrows, or empty-handed in a raid — and in the settlement, now and then, says what it needs.",
      "Any tree can be felled now, not just the big ones by the cabin.",
      "Every action takes a moment and fills the little wheel — hold F. Let go before the next.",
      "Hewing the door shows the saw going; building, raising and making furniture show the hammer; carving and dressing game show the knife.",
      "Swinging an axe makes a whoosh, not a click.",
      "Logs look like logs: bark round the sides and growth rings on the sawn ends — on the stack, in the woodshed, at the building sites and where a tree fell.",
      "No more chins standing out on everyone's faces.",
      "The front door of the house in Hamburg is an old, weathered oxblood rather than bright red.",
      "The objective in the corner is bigger.",
      "Fixed: sprinting while your brother or sister talked on the road could hide what they were saying while the voice went on.",
    ],
  },
  {
    v: "0.15", date: "28 September 2026", title: "Raiders on the road",
    items: [
      "Raiders: from the second week a band comes up the road at dusk, every week or so and bigger as the settlement grows. They make for the stores and run back down the road with logs, rye and money.",
      "Stop them with the axe — three strokes — or a couple of good arrows, and whatever they were carrying goes back in the stores. They fight back: a blow knocks you back, winded, and drops what you're carrying.",
      "While they're about, settlers take cover by the fire, and nobody goes to bed. A settlement that has been robbed is less content for days.",
      "The watch: once the settlement knows Policing, a settler can be put on watch, and goes after raiders with you.",
      "Free play has the deer and hares back in the forest, every day.",
      "The Reckoning: when the men come up the road, everyone at the fire turns to look, and watches them all the way up.",
    ],
  },
  {
    v: "0.14", date: "28 September 2026", title: "A bow you draw, a forest you can walk, and a settlement that grows",
    items: [
      "The bow: hold right-click to draw — the view closes in on the middle of the screen — and let go to loose. Hold it at full draw too long and your arms start to shake, and the shot with them.",
      "A real crosshair: it opens wide with the bow out and closes in as you draw, and turns red over anything you can hunt. Never over a person.",
      "No more fence round the deer ride or the cabin: once you live there, you can walk a long way into the forest all round it.",
      "The settlement grows: when the buildings fill what room there is, your brother or sister says so, the edge moves out into the forest, and everyone — you too — turns to felling the trees past the old edge until the ground is clear to build on.",
      "Felled trees grow back, in every chapter, out of sight. Cleared ground stays cleared.",
      "After Henning gives you the bow, you have to walk back to the cabin before your brother or sister can see it.",
      "Choosing someone's work from the list works with the mouse now — the click no longer grabs the mouse back into the game.",
      "The view no longer turns by itself when the cursor rests near the edge of the window.",
      "Both arms come in from the right when you hold the axe.",
      "Conversations stay on top: the stamina bar, tips and hints no longer cover what is being said while you run.",
      "On Balanced or Performance graphics the sky no longer goes black.",
      "The money is Deutsche Mark now — DM — as in the first Forester. Selling the house on the Deichstraße brings in 70 DM, to spend on research.",
      "A second trader: Tobias the pedlar, out of Lübeck, comes up the road every fourth day with arrows, tools, iron, stone and salt pork, and buys planks, bricks and meat. Henning still comes every third day, and both come from the harvest on.",
      "The government says where DM comes from — the traders, and when each is next due, or a market — and the board tells you when you're short.",
      "A sign over every building site: its logs and stone, planks or bricks so far, and when it's ready for your hands.",
      "The woodshed: once it's up, the old stack and its platform are cleared away and the logs go in under its roof — and it's only as full as your store.",
      "The log stack by the cabin shows how full the store really is, and making furniture says what it cost.",
      "Tasks already done come off the board: rye reaped by the farmers counts as reaped, and a cabin with room already standing takes Jan and Liesel in.",
      "Press G for the government — the game tells you so, once you have a settlement.",
      "Paths: choose Path in the plans (B) and lay a trodden way between the houses a strip at a time, free — the plan stays up for the next strip until you press Esc. They turn to cobbles once the town is brick, and you hear the difference underfoot.",
      "Right-click picks things up again with the bow out (arrows too); it only draws when you are not looking at something to take.",
    ],
  },
  {
    v: "0.13", date: "28 September 2026", title: "The chase by night, stones to throw, and breath you can feel",
    items: [
      "The chase through Hamburg now happens that night, under the street lamps, after the square empties — and the marsh gate that follows is a misty night too.",
      "The chase is longer and harder: four of the watch now, one coming down the north street after the bell, and you have to run the whole length of the narrow alley with them on your heels.",
      "The watchman who used to plant himself in the mouth of the alley, so nobody could get past, now races you to it from round the corner. Get there first and the way is always open.",
      "Stones in the alley: pick one up (F) and click to throw it. The nearest watchman who hears it land goes to see what it was, looks about, and goes back — leaving a gap.",
      "In tense moments — the chase, creeping past the watch, hiding from the charcoal buyer — and whenever you are out of breath, your view rises and falls with your breathing.",
      "Talking to someone is an action now: hold F for a moment, and they stop what they are doing and turn to you while you speak.",
      "The watchman by the marsh gate is easier to pass: he sees less far, sweeps a narrower arc, and every so often turns to check the gate behind him — that's your moment.",
      "FPS boosters in Settings: graphics presets (High, Balanced, Performance), render scale, auto resolution that drops when the frame rate falls, soft, hard or no shadows, draw distance, a frame cap, and an FPS counter.",
    ],
  },
  {
    v: "0.12", date: "28 September 2026", title: "The government: your nation, Forester's tech tree, and everyone in it",
    items: [
      "Press G for the government. The Nation page names your settlement and what it has become — camp, hamlet, village, town or city — with its people and beds, how content they are and why, days of food and of firewood, the treasury, what the scholars know, everything in the stores, and every building by its style.",
      "The tech tree is the first Forester's own, node for node: Growth, Military Philosophy, Industry and Exploration, sixty-six technologies at Forester's prices, paid in Marks and researched over time. Click a lit node to begin; search for anything by name.",
      "In free play, building waits on knowledge as it does in Forester: Baking for the bakery, Trading for the market, Township for the town hall, Masonry, Millwork, Mining and Smelting for the works, Ministry for the church. The plans say what each still needs.",
      "What is learnt is put to work: quicker felling, more logs from every tree, saplings that grow back twice as fast, crops that ripen sooner, three to a cabin, faster walking once there are horses, busier quarries and mines, a blast furnace's double iron, better market prices, and less hunger. The trades and forces Reckoning hasn't built yet are learnt now and used when they come.",
      "The People page lists everyone in the nation — you, your family and every settler — with their work, where they sleep, what they are doing right now and what they have, and a button to set their work.",
      "Contentment matters: where people are unhappy — hungry, cold, or without a bed — nobody new will stay.",
    ],
  },
  {
    v: "0.11", date: "28 September 2026", title: "From cabin to city: the works, and rebuilding in the style of the age",
    items: [
      "The works: a quarry for stone, a sawmill for planks, a brickworks, a mine for iron ore, a smelter for iron, and a forge whose tools make everyone a quarter quicker. Each wants a pair of hands.",
      "A market that sells your surplus for Marks every day, a town hall, and a church.",
      "Rebuild what you've built, in the style of its age: F at the front of a cabin, bakery or any works to rebuild it in timber and plaster as Hamburg does, then in red brick as the Hanse does, then — once the town hall is brick and you hold a charter — in stucco and glass, as a city builds now. The well becomes a fountain.",
      "As the town grows grander the ground between the houses is cobbled, and then paved, with street lamps round the square.",
      "Talk to someone (F) and choose their work from a list: every trade open to them, what it takes in and puts out, and how many are at it already.",
      "Buildings can want stone, planks or bricks as well as logs; haulers bring them from the stores, or you can.",
      "The board tells you the next step: open a quarry, build a sawmill, rebuild a cabin in timber, raise a town hall.",
    ],
  },
  {
    v: "0.10", date: "28 September 2026", title: "The year goes round: night, winter, bread and Henning's cart",
    items: [
      "At dusk everyone stops work and goes home — two to each cabin, and anyone without a bed lies down by the fire. Your brother or sister sleeps on the other pallet in your own cabin.",
      "An eight-day year: spring, summer, autumn and winter. In winter the snow comes in, nothing grows, and every hearth burns a log a day; two cold nights with the stack empty, and someone goes back down the road.",
      "The bakery: a baker turns two rye into three loaves, and a loaf feeds twice what grain does. Everyone eats bread first.",
      "Henning's cart comes up the road every third morning. Sell him logs, bread and rye for Marks, and buy rye, arrows, a better saw (a log more from every tree) or iron axe heads (quicker felling).",
      "The board at the top names the season and says what the settlement needs next, firewood before winter included.",
      "The blizzard night in The First Winter has three more logs to burn.",
      "Buildings are drawn in the style of their age: the models for timber-frame, brick and modern houses are made, ready for upgrading.",
    ],
  },
  {
    v: "0.9", date: "28 September 2026", title: "Hunting, footsteps, and a sharper watch",
    items: [
      "Before you dig, you hunt: Henning gives you his old bow and a dozen arrows, and the woods east of the cabin open. Creep up on the roe and the hares, draw, and let go; pull your arrows back out of wherever they land.",
      "Footsteps sound like what you're walking on: grass, leaves and needles, the dirt of the track, cobbles, floorboards, snow, the marsh. You hear other people's too, and the watch walks heavy.",
      "People carrying a lantern or a torch walk properly now, instead of gliding. The charcoal buyer walks faster.",
      "The watch sees you more easily: a wider eye, farther even when you crouch, and they hear you walk up behind them.",
      "Martinmas is harder: the charcoal buyer is quicker and sharper, and before he goes he stands at the edge of the trees and swings his lantern across them.",
      "No more stone ledge round the foot of the cabin.",
      "The hands have no thumbs sticking out, and the camera is first person only.",
    ],
  },
  {
    v: "0.8.1", date: "28 September 2026", title: "Jakob's map, and fixes",
    items: [
      "Jakob gives you a map at the end of your errand — a copy of the one on the counting-house wall — and shows you how to read it. Until then there is no map.",
      "On the map (J), the mouse wheel zooms in on whatever is under the cursor, and dragging moves the sheet.",
      "The marker no longer points through houses: when there's no straight way, it stands on the next corner of the way there. The distance is the whole way.",
      "Fixed: the game could stop when Father crossed the room to you on the night they came for him.",
      "You can't sprint while the stamina bar is red. It turns red when you're winded, amber when you're getting low.",
      "What people say while you walk now sits above the stamina bar, instead of behind it.",
    ],
  },
  {
    v: "0.8", date: "28 September 2026", title: "The end of the story: Harvest Home and The Reckoning",
    items: [
      "Chapter XII, Harvest Home: two more come up the road with nowhere to sleep. Raise them a cabin, reap the rye, set someone to new work and furnish your own cabin — then the harvest supper, and Henning's news.",
      "Chapter XIII, The Reckoning: they come for you with a warrant. Bring everyone to the fire, and stand there with them. Jakob comes up the road with your father's ledger — and the choice of where home is.",
      "Free play is now chapter XIV. The board at the top says what the settlement needs next.",
      "Talk to a settler (F) to change their work: felling, carrying, or the fields.",
      "Hunger: everyone eats rye every day. A day with none and you're warned; two, and the newest to come goes back down the road.",
      "Every night of the story now ends in bed in the cabin, the naming night of chapter XI included.",
    ],
  },
  {
    v: "0.7", date: "28 September 2026", title: "A roof over you: into the cabin, and to bed",
    items: [
      "The cabin can be entered: the door swings in on its hinge (F to open or shut it), and inside there's a plank floor, a stone hearth under the chimney, and two straw pallets along the wall.",
      "Nights end in bed now, not out by the fire: after the talk at the fire, go in and lie down. The blizzard night of The First Winter is kept inside, at the hearth, with the door shut on the snow.",
      "Furnish the cabin: press B while you're inside for a bed, a table, a bench, a chest, a shelf or a rye barrel, made from logs off the stack (a pallet costs rye). Walk it into place and turn it with R.",
      "In free play, your bed takes you through the night to morning.",
      "People walk round things instead of through them: tables, carts, the well, the cabin walls, and you.",
      "Fixed: in The First Winter nothing told you what to do after splitting the firewood. The task list now shows, with a marker to the block, the nearest moss and the wall in turn. Chapter XI marks its tasks too.",
      "Chapter numbers show beside their numerals: X (10).",
      "The gables of the cabin sit down on the top log; no daylight between them.",
    ],
  },
  {
    v: "0.6", date: "28 September 2026", title: "The settlement: X. The Stranger, XI. Forester, and free play",
    items: [
      "Chapter X, The Stranger: in spring a widow and her son come up the road. Plan them a cabin (B), and raise it with logs you fell and carry — Marta carries too.",
      "Chapter XI, Forester: high summer, six of you. Reap the rye, build a well and a woodshed, dig a second field — then name the place, at the fire, with everyone there. The tutorial ends here.",
      "Free play: the settlement is yours. Days turn to night and back; stumps grow back into trees; fields ripen; people come up the road when there are beds and bread.",
      "Plans (B): cabins, a woodshed, a well, fields. A building follows your eye as a green ghost (red where it won't fit); R turns it.",
      "Settlers work: woodcutters fell and stack, haulers carry logs from the stack to building sites, farmers keep the fields.",
      "Fixed: you could only dig a strip of the field from its very middle. Now anywhere along it will do.",
      "Fixed: the ground round the rebuilt cabin looked like planks.",
      "The stamina bar sits just above the hotbar.",
    ],
  },
  {
    v: "0.5", date: "28 September 2026", title: "Part Two begins: Seed Before Frost",
    items: [
      "Chapter VIII, Martinmas: a cart comes up the road at dusk. Put out the fire, get into the trees, and keep out of the charcoal buyer's lantern while he counts everything you have. Then Henning comes to the fire with a name, and a warning.",
      "Chapter IX, The First Winter: snow on the ground, on the roof and on every bough. Split firewood, pull moss from under the snow to chink the walls — and then keep the fire alive through a blizzard night until dawn.",
      "A hotbar along the bottom of the screen: what you have to hand, in nine slots. Press 1 to 9 to pick one — the axe's slot takes it out or puts it away.",
      "The cursor is a small hollow square: yellow over something you can use, turning slowly green as you use it.",
      "The axe is in your own two hands, your sleeves running back to your shoulders, and it swings across in front of you, side-on, the head leading.",
      "Snow: it lies on whatever faces the sky, and falls, lightly or in a blizzard.",
      "The map is explored as you go: what you have not seen is blank parchment, and the ink spreads as you walk. What you have seen is remembered.",
      "Wrong turns on the road are barred a few steps in; your brother or sister still tells you why.",
      "Dialogue and narration write themselves out a letter at a time, each with a small click. Press Space once to finish a line, again to move on.",
      "Trees now hide you from anyone looking for you.",
      "Fixed: the watchman at the marsh gate walked straight into the cart.",
      "A new chapter, VII. Seed Before Frost, the first of Part Two: Roots. The morning after the cabin stands, you carry wood down the smoking track to the charcoal burner's camp and trade it for rye seed and a spade — if he will trade with a stranger who talks like Hamburg. Then dig your first field beside the cabin, and sow it before the frost.",
      "Henning, the charcoal burner, and his camp: a kiln smoking under its turf, his lean-to, his woodpile, at the end of the fourth fork on the road.",
      "Chapters you have not reached yet are no longer shown in the Chapters list at all.",
      "Doors creak as they open, and shut with a thud and the click of the latch. A line of dialogue arrives with a soft tick.",
      "Fixed: people's clothes came apart from their bodies when they twisted or bent. Coats, waistcoats and cuffs now move with the body under them.",
      "Fixed: you stood up at the table instead of sitting on the bench.",
      "Fixed: your brother or sister stood in your way when the men came to the door, and walked into the table afterwards.",
      "Fixed: the red front door was made of bricks. It is painted wood again.",
      "Fixed: cobbles covered the harbour where the water should be.",
      "Fixed: you could not leave the cabin by the road.",
    ],
  },
  {
    v: "0.4", date: "28 September 2026", title: "A painting on the front door",
    items: [
      "The title screen hangs a new picture: the burned cabin at dawn, painted as a Dutch landscape of the 1660s would have painted it.",
      "Father looks like the grain merchant he is: a beard going grey, a heavier brow and jaw. The round cheeks are gone from everyone's faces.",
      "The trees are rebuilt: spruces with ragged, drooping tiers, pines with flat broken crowns, birches with loose clumps of leaves, and no two quite the same green. Walls, timber, stone and bark have grain and weathering instead of flat colour.",
      "Press T for your inventory: a grid of slots showing what is in your hands, what is on you, and at the cabin what is stacked and built. Hover a slot to read it.",
      "No more voices: every line is read, not spoken, and the Voices setting is gone.",
      "The cabin and the burned ruin are now models made in Blender: round logs crossing at the corners, a plank door with iron straps, a boarded roof, and a stone chimney that outlasted the fire.",
      "Everyone is new, made in Blender: you, your brother or sister, Father, Jakob, the magistrate, the watch, Frau Albers and the people of Hamburg. Each has a real face (eyes, brows, nose, lips, a beard where they wear one), clothes of 1683 — long coats with deep cuffs and a cravat, or a laced bodice, full skirt and apron — and a skeleton that walks, runs, sits, swings an axe, and holds a torch, a lantern or the magistrate's writ. The crowd is still varied: each townsperson wears their own colours.",
      "Real textures everywhere: photographed wood grain, lime plaster, fieldstone, brick, clay roof tiles, bark, spruce needles and woven cloth, laid over every building, tree, model and piece of clothing. Hamburg's streets are real cobbles; the woods have a forest floor of needles and moss; the marsh is a meadow.",
      "Nights, dusk and mist are no longer too dark to see: a candle-lit room is dim, not black.",
      "Your brother or sister teaches you the game as you go: how to walk and look, open doors, run, crouch and lean, use the map and inventory, swing the axe and stack the logs — each the first time you need it, in their own words, with the keys shown underneath. Once you have learned a thing they do not say it again.",
      "A new map, drawn as a map of 1683 would be: ink on parchment, the forest stamped tree by tree, roads in brown, water hatched, the town in red. Press J for the whole map, with its title, compass rose and scale.",
      "The road is a real country road now: a narrow cart track, two wheel ruts with grass up the middle, stones kicked to the sides, its edges ragged. The forks are fainter tracks that the grass is taking back.",
      "Running costs breath everywhere now, not only in the chase. The stamina bar shows while you are short of it.",
      "The road out of Hamburg winds, and forks seven times. Your brother or sister knows the way and tells you at each fork, and calls you back if you take the wrong track. The first forks have signposts; every wrong track ends at a fallen tree.",
      "Look back from the start of the road and Hamburg is there across the fields: its walls and bastions, windmills, a sea of roofs, and the five green spires.",
      "The fellable spruces and the ships in the harbour are Blender models now.",
      "You can see the axe in your hands, and it swings the way a felling axe does: back over the shoulder and level through the trunk.",
      "Skirts and coat-tails swing with the legs when people walk.",
      "Fixed: a tree felled on the edge of the cabin's ground could drop its logs where you could not reach them. Logs now always land within reach, and logs left on the ground are kept in the save.",
      "Press M to take the mouse into the game and look around, and M again to let it go without pausing. Where the browser will not lock the mouse, M looks around with the cursor hidden instead, and resting the cursor at the edge of the screen keeps turning.",
    ],
  },
  {
    v: "0.3", date: "28 September 2026", title: "On the website, and ready for Blender",
    items: [
      "Forester: Reckoning now has its own page on the DeadlyDog Productions website, and the early build can be played from there.",
      "A Graphics setting: High keeps the soft shadows and full resolution; Low turns shadows off and renders fewer pixels, for laptops that struggle in the woods.",
      "Models made in Blender can now replace the built-in ones. Export a .glb into reckoning/models/, list it in manifest.json, and the cabin, the ruin, the spruces, the ships and every character can be swapped without touching the code.",
      "This update log.",
    ],
  },
  {
    v: "0.2", date: "28 September 2026", title: "Fairer, clearer, louder",
    items: [
      "The marsh gate can actually be passed. The gatehouse wall had nearly sealed the way to the small door; there is a proper passage now.",
      "The watch is fairer: they see less far, turn less, take longer to be sure of you and forget you sooner. Two more watchmen walk the streets further out, so wandering off is noticed.",
      "The small door beside the marsh gate is dressed in pale stone, has a lantern over it, and glows through walls while you are making for it.",
      "The front door of the house was being hidden by a strip of wall. You can see it now — it is painted red.",
      "Every light has something making it: candles on the table, the desk, the mantel and by the door, and street lamps on posts along the streets.",
      "The first evening is an ordinary evening. Nobody warns you. The knocking comes as a surprise.",
      "Lean round corners with Q and E. Talk, take and open things with F (or right click).",
      "Hold Z to zoom in.",
      "A minimap in the corner: you, your brother or sister, the watch and which way they are looking, and where you are going.",
      "The chase through the square is a real chase: faster watchmen, one who cuts you off, and breath that runs out.",
      "Getting caught brings up a red screen, a different line every time, and a quote that writes itself in underneath.",
      "Voices: everyone speaks their lines aloud, each with their own voice. (They are your browser's voices; turn them off in Settings.)",
      "Flies in the day, moths round the lamps at dusk, fireflies in the woods at night — and now and then one past your ear.",
      "The menus and the HUD are dark green.",
      "Better-made people: shaped bodies, faces with eyes and brows, hands, buttons and buckles, coats with tails, skirts with hems, hats that look like hats.",
      "The harbour opens onto water that goes to the horizon.",
      "Fixed: the log stack by the cabin froze the game once it held more than ten logs.",
      "Fixed: the misty morning at the marsh gate and the dusk at the cabin were too dark to see by.",
    ],
  },
  {
    v: "0.1", date: "27 September 2026", title: "The first build",
    items: [
      "Forester's story, lived in first person in 3D: Part One, Ashes, in six chapters.",
      "I. The House by the Harbour — Hamburg, 1683. An errand for Father, down to the warehouse on the quay, and home for supper.",
      "II. Papers and Torches — the knocking at night, the magistrate's writ, and Father taken.",
      "III. The Square at Dawn — the crowd that had bought our bread, watching in silence.",
      "IV. The Marsh Gate — through the lanes, past the watch, to the small door in the wall.",
      "V. Far, Far Away — the long road into the old woods, until the bells fade.",
      "VI. — what waits at the end of the road, and the work of making it home.",
      "Play as the Brother or the Sister; the other is beside you all the way.",
      "First person or over the shoulder (V). Progress kept at every chapter and as you work.",
      "Music and sound built at runtime, with the first Forester's sound engine underneath.",
    ],
  },
];
