// ===========================================================================
//  FORESTER: RECKONING — Copyright (c) 2026 Roan Fraese / DeadlyDog Productions
// ===========================================================================

// WHAT HAS CHANGED — the update log on the front door, newest first. It is
// kept beside the code it describes, as the first Forester's is.

export const CHANGELOG = [
  {
    v: "0.10", date: "28 September 2026", title: "The year goes round: night, winter, bread and Henning's cart",
    items: [
      "At dusk everyone stops work and goes home — two to each cabin, and anyone without a bed lies down by the fire. Your brother or sister sleeps on the other pallet in your own cabin.",
      "An eight-day year: spring, summer, autumn and winter. In winter the snow comes in, nothing grows, and every hearth burns a log a day; two cold nights with the stack empty, and someone goes back down the road.",
      "The bakery: a baker turns two rye into three loaves, and a loaf feeds twice what grain does. Everyone eats bread first.",
      "Henning's cart comes up the road every third morning. Sell him logs, bread and rye for Marks, and buy rye, arrows, a better saw (a log more from every tree) or iron axe heads (quicker felling).",
      "The board at the top names the season and says what the settlement needs next, firewood before winter included.",
      "The blizzard night in The First Winter has three more logs to burn.",
      "Buildings are drawn in the style of their age: the models for timber-frame, brick and modern houses are made, ready for upgrading.",
    ],
  },
  {
    v: "0.9", date: "28 September 2026", title: "Hunting, footsteps, and a sharper watch",
    items: [
      "Before you dig, you hunt: Henning gives you his old bow and a dozen arrows, and the woods east of the clearing open. Creep up on the roe and the hares, draw, and let go; pull your arrows back out of wherever they land.",
      "Footsteps sound like what you're walking on: grass, leaves and needles, the dirt of the track, cobbles, floorboards, snow, the marsh. You hear other people's too, and the watch walks heavy.",
      "People carrying a lantern or a torch walk properly now, instead of gliding. The charcoal buyer walks faster.",
      "The watch sees you more easily: a wider eye, farther even when you crouch, and they hear you walk up behind them.",
      "Martinmas is harder: the charcoal buyer is quicker and sharper, and before he goes he stands at the edge of the trees and swings his lantern across them.",
      "No more stone ledge round the foot of the cabin.",
      "The hands have no thumbs sticking out, and the camera is first person only.",
    ],
  },
  {
    v: "0.8.1", date: "28 September 2026", title: "Jakob's map, and fixes",
    items: [
      "Jakob gives you a map at the end of your errand — a copy of the one on the counting-house wall — and shows you how to read it. Until then there is no map.",
      "On the map (J), the mouse wheel zooms in on whatever is under the cursor, and dragging moves the sheet.",
      "The marker no longer points through houses: when there's no straight way, it stands on the next corner of the way there. The distance is the whole way.",
      "Fixed: the game could stop when Father crossed the room to you on the night they came for him.",
      "You can't sprint while the stamina bar is red. It turns red when you're winded, amber when you're getting low.",
      "What people say while you walk now sits above the stamina bar, instead of behind it.",
    ],
  },
  {
    v: "0.8", date: "28 September 2026", title: "The end of the story: Harvest Home and The Reckoning",
    items: [
      "Chapter XII, Harvest Home: two more come up the road with nowhere to sleep. Raise them a cabin, reap the rye, set someone to new work and furnish your own cabin — then the harvest supper, and Henning's news.",
      "Chapter XIII, The Reckoning: they come for you with a warrant. Bring everyone to the fire, and stand there with them. Jakob comes up the road with your father's ledger — and the choice of where home is. Then carve his name into the beam you kept.",
      "Free play is now chapter XIV. The board at the top says what the settlement needs next.",
      "Talk to a settler (F) to change their work: felling, carrying, or the fields.",
      "Hunger: everyone eats rye every day. A day with none and you're warned; two, and the newest to come goes back down the road.",
      "Every night of the story now ends in bed in the cabin, the naming night of chapter XI included.",
    ],
  },
  {
    v: "0.7", date: "28 September 2026", title: "A roof over you: into the cabin, and to bed",
    items: [
      "The cabin can be entered: the door swings in on its hinge (F to open or shut it), and inside there's a plank floor, a stone hearth under the chimney, and two straw pallets along the wall.",
      "Nights end in bed now, not out by the fire: after the talk at the fire, go in and lie down. The blizzard night of The First Winter is kept inside, at the hearth, with the door shut on the snow.",
      "Furnish the cabin: press B while you're inside for a bed, a table, a bench, a chest, a shelf or a rye barrel, made from logs off the stack (a pallet costs rye). Walk it into place and turn it with R.",
      "In free play, your bed takes you through the night to morning.",
      "People walk round things instead of through them: tables, carts, the well, the cabin walls, and you.",
      "Fixed: in The First Winter nothing told you what to do after splitting the firewood. The task list now shows, with a marker to the block, the nearest moss and the wall in turn. Chapter XI marks its tasks too.",
      "Chapter numbers show beside their numerals: X (10).",
      "The gables of the cabin sit down on the top log; no daylight between them.",
    ],
  },
  {
    v: "0.6", date: "28 September 2026", title: "The settlement: X. The Stranger, XI. Forester, and free play",
    items: [
      "Chapter X, The Stranger: in spring a widow and her son come up the road. Plan them a cabin (B), and raise it with logs you fell and carry — Marta carries too.",
      "Chapter XI, Forester: high summer, six of you. Reap the rye, build a well and a woodshed, dig a second field — then name the place, at the fire, with everyone there. The tutorial ends here.",
      "Free play: the settlement is yours. Days turn to night and back; stumps grow back into trees; fields ripen; people come up the road when there are beds and bread.",
      "Plans (B): cabins, a woodshed, a well, fields. A building follows your eye as a green ghost (red where it won't fit); R turns it.",
      "Settlers work: woodcutters fell and stack, haulers carry logs from the stack to building sites, farmers keep the fields.",
      "Fixed: you could only dig a strip of the field from its very middle. Now anywhere along it will do.",
      "Fixed: the ground round the rebuilt cabin looked like planks.",
      "The stamina bar sits just above the hotbar.",
    ],
  },
  {
    v: "0.5", date: "28 September 2026", title: "Part Two begins: Seed Before Frost",
    items: [
      "Chapter VIII, Martinmas: a cart comes up the road at dusk. Put out the fire, get into the trees, and keep out of the charcoal buyer's lantern while he counts everything you have. Then Henning comes to the fire with a name, and a warning.",
      "Chapter IX, The First Winter: snow on the clearing, on the roof and on every bough. Split firewood, pull moss from under the snow to chink the walls — and then keep the fire alive through a blizzard night until dawn.",
      "A hotbar along the bottom of the screen: what you have to hand, in nine slots. Press 1 to 9 to pick one — the axe's slot takes it out or puts it away.",
      "The cursor is a small hollow square: yellow over something you can use, turning slowly green as you use it.",
      "The axe is in your own two hands, your sleeves running back to your shoulders, and it swings across in front of you, side-on, the head leading.",
      "Snow: it lies on whatever faces the sky, and falls, lightly or in a blizzard.",
      "The map is explored as you go: what you have not seen is blank parchment, and the ink spreads as you walk. What you have seen is remembered.",
      "Wrong turns on the road are barred a few steps in; your brother or sister still tells you why.",
      "Dialogue and narration write themselves out a letter at a time, each with a small click. Press Space once to finish a line, again to move on.",
      "Trees now hide you from anyone looking for you.",
      "Fixed: the watchman at the marsh gate walked straight into the cart.",
      "A new chapter, VII. Seed Before Frost, the first of Part Two: Roots. The morning after the cabin stands, you carry wood down the smoking track to the charcoal burner's camp and trade it for rye seed and a spade — if he will trade with a stranger who talks like Hamburg. Then dig your first field beside the cabin, and sow it before the frost.",
      "Henning, the charcoal burner, and his camp: a kiln smoking under its turf, his lean-to, his woodpile, at the end of the fourth fork on the road.",
      "Chapters you have not reached yet are no longer shown in the Chapters list at all.",
      "Doors creak as they open, and shut with a thud and the click of the latch. A line of dialogue arrives with a soft tick.",
      "Fixed: people's clothes came apart from their bodies when they twisted or bent. Coats, waistcoats and cuffs now move with the body under them.",
      "Fixed: you stood up at the table instead of sitting on the bench.",
      "Fixed: your brother or sister stood in your way when the men came to the door, and walked into the table afterwards.",
      "Fixed: the red front door was made of bricks. It is painted wood again.",
      "Fixed: cobbles covered the harbour where the water should be.",
      "Fixed: you could not leave the clearing by the road.",
    ],
  },
  {
    v: "0.4", date: "28 September 2026", title: "A painting on the front door",
    items: [
      "The title screen hangs a new picture: the burned cabin at dawn, painted as a Dutch landscape of the 1660s would have painted it.",
      "Father looks like the grain merchant he is: a beard going grey, a heavier brow and jaw. The round cheeks are gone from everyone's faces.",
      "The trees are rebuilt: spruces with ragged, drooping tiers, pines with flat broken crowns, birches with loose clumps of leaves, and no two quite the same green. Walls, timber, stone and bark have grain and weathering instead of flat colour.",
      "Press T for your inventory: a grid of slots showing what is in your hands, what is on you, and at the clearing what is stacked and built. Hover a slot to read it.",
      "No more voices: every line is read, not spoken, and the Voices setting is gone.",
      "The cabin and the burned ruin are now models made in Blender: round logs crossing at the corners, a plank door with iron straps, a boarded roof, and a stone chimney that outlasted the fire.",
      "Everyone is new, made in Blender: you, your brother or sister, Father, Jakob, the magistrate, the watch, Frau Albers and the people of Hamburg. Each has a real face (eyes, brows, nose, lips, a beard where they wear one), clothes of 1683 — long coats with deep cuffs and a cravat, or a laced bodice, full skirt and apron — and a skeleton that walks, runs, sits, swings an axe, and holds a torch, a lantern or the magistrate's writ. The crowd is still varied: each townsperson wears their own colours.",
      "Real textures everywhere: photographed wood grain, lime plaster, fieldstone, brick, clay roof tiles, bark, spruce needles and woven cloth, laid over every building, tree, model and piece of clothing. Hamburg's streets are real cobbles; the woods have a forest floor of needles and moss; the marsh is a meadow.",
      "Nights, dusk and mist are no longer too dark to see: a candle-lit room is dim, not black.",
      "Your brother or sister teaches you the game as you go: how to walk and look, open doors, run, crouch and lean, use the map and inventory, swing the axe and stack the logs — each the first time you need it, in their own words, with the keys shown underneath. Once you have learned a thing they do not say it again.",
      "A new map, drawn as a map of 1683 would be: ink on parchment, the forest stamped tree by tree, roads in brown, water hatched, the town in red. Press J for the whole map, with its title, compass rose and scale.",
      "The road is a real country road now: a narrow cart track, two wheel ruts with grass up the middle, stones kicked to the sides, its edges ragged. The forks are fainter tracks that the grass is taking back.",
      "Running costs breath everywhere now, not only in the chase. The stamina bar shows while you are short of it.",
      "The road out of Hamburg winds, and forks seven times. Your brother or sister knows the way and tells you at each fork, and calls you back if you take the wrong track. The first forks have signposts; every wrong track ends at a fallen tree.",
      "Look back from the start of the road and Hamburg is there across the fields: its walls and bastions, windmills, a sea of roofs, and the five green spires.",
      "The fellable spruces and the ships in the harbour are Blender models now.",
      "You can see the axe in your hands, and it swings the way a felling axe does: back over the shoulder and level through the trunk.",
      "Skirts and coat-tails swing with the legs when people walk.",
      "Fixed: a tree felled on the edge of the clearing could drop its logs where you could not reach them. Logs now always land within reach, and logs left on the ground are kept in the save.",
      "Press M to take the mouse into the game and look around, and M again to let it go without pausing. Where the browser will not lock the mouse, M looks around with the cursor hidden instead, and resting the cursor at the edge of the screen keeps turning.",
    ],
  },
  {
    v: "0.3", date: "28 September 2026", title: "On the website, and ready for Blender",
    items: [
      "Forester: Reckoning now has its own page on the DeadlyDog Productions website, and the early build can be played from there.",
      "A Graphics setting: High keeps the soft shadows and full resolution; Low turns shadows off and renders fewer pixels, for laptops that struggle in the woods.",
      "Models made in Blender can now replace the built-in ones. Export a .glb into reckoning/models/, list it in manifest.json, and the cabin, the ruin, the spruces, the ships and every character can be swapped without touching the code.",
      "This update log.",
    ],
  },
  {
    v: "0.2", date: "28 September 2026", title: "Fairer, clearer, louder",
    items: [
      "The marsh gate can actually be passed. The gatehouse wall had nearly sealed the way to the small door; there is a proper passage now.",
      "The watch is fairer: they see less far, turn less, take longer to be sure of you and forget you sooner. Two more watchmen walk the streets further out, so wandering off is noticed.",
      "The small door beside the marsh gate is dressed in pale stone, has a lantern over it, and glows through walls while you are making for it.",
      "The front door of the house was being hidden by a strip of wall. You can see it now — it is painted red.",
      "Every light has something making it: candles on the table, the desk, the mantel and by the door, and street lamps on posts along the streets.",
      "The first evening is an ordinary evening. Nobody warns you. The knocking comes as a surprise.",
      "Lean round corners with Q and E. Talk, take and open things with F (or right click).",
      "Hold Z to zoom in.",
      "A minimap in the corner: you, your brother or sister, the watch and which way they are looking, and where you are going.",
      "The chase through the square is a real chase: faster watchmen, one who cuts you off, and breath that runs out.",
      "Getting caught brings up a red screen, a different line every time, and a quote that writes itself in underneath.",
      "Voices: everyone speaks their lines aloud, each with their own voice. (They are your browser's voices; turn them off in Settings.)",
      "Flies in the day, moths round the lamps at dusk, fireflies in the woods at night — and now and then one past your ear.",
      "The menus and the HUD are dark green.",
      "Better-made people: shaped bodies, faces with eyes and brows, hands, buttons and buckles, coats with tails, skirts with hems, hats that look like hats.",
      "The harbour opens onto water that goes to the horizon.",
      "Fixed: the log stack in the clearing froze the game once it held more than ten logs.",
      "Fixed: the misty morning at the marsh gate and the dusk in the clearing were too dark to see by.",
    ],
  },
  {
    v: "0.1", date: "27 September 2026", title: "The first build",
    items: [
      "Forester's story, lived in first person in 3D: Part One, Ashes, in six chapters.",
      "I. The House by the Harbour — Hamburg, 1683. An errand for Father, down to the warehouse on the quay, and home for supper.",
      "II. Papers and Torches — the knocking at night, the magistrate's writ, and Father taken.",
      "III. The Square at Dawn — the crowd that had bought our bread, watching in silence.",
      "IV. The Marsh Gate — through the lanes, past the watch, to the small door in the wall.",
      "V. Far, Far Away — the long road into the old woods, until the bells fade.",
      "VI. The Clearing — an old axe, twenty logs, a door, and the burned cabin raised again.",
      "Play as the Brother or the Sister; the other is beside you all the way.",
      "First person or over the shoulder (V). Progress kept at every chapter and as you work in the clearing.",
      "Music and sound built at runtime, with the first Forester's sound engine underneath.",
    ],
  },
];
