#!/usr/bin/env python3
"""Draw the action bar's icons as pixel grids, and emit them as inline SVG.

The bar used nine emoji. Emoji are full-colour, modern, and drawn by whichever
operating system the player happens to be on, so the game looked different on
every machine and none of those looks belonged to 1683.

These are authored as 16x16 grids of characters — the same medium as the rest of
the game's art, just small — and emitted as SVG rectangles with fill
"currentColor", which is the part a PNG could not do: the icon takes the colour
of the text beside it, so it dims with a disabled button and lifts on hover
without anyone maintaining a second set of images.

Horizontal runs are merged into single rects, so each icon is a handful of them.

    python3 tools/icons.py            # print the SVG for each icon
    python3 tools/icons.py --write    # write them into index.html
"""
import pathlib
import re
import sys

# '#' is drawn, anything else is not. 16 rows of 16.
ICONS = {
    # a house going up: roof, and a frame below it
    "build": """
    ................
    .......#........
    ......###.......
    .....#####......
    ....#######.....
    ...#########....
    ..###########...
    .#############..
    ..#############.
    ..##.......###..
    ..##.#####.###..
    ..##.#...#.###..
    ..##.#...#.###..
    ..##.#...#.###..
    ..#############.
    ................
    """,
    # an anvil on its stock
    "craft": """
    ................
    ................
    ................
    ..###########...
    ..#############.
    ..##############
    ..#############.
    ..###########...
    .....######.....
    .....#####......
    .....#####......
    ....#######.....
    ...#########....
    ..###########...
    ..###########...
    ................
    """,
    # a road running away from you, with a broken line down the middle
    "roads": """
    ................
    ......#..#......
    ......#..#......
    .....#....#.....
    .....#.##.#.....
    .....#.##.#.....
    ....#......#....
    ....#......#....
    ...#...##...#...
    ...#...##...#...
    ..#..........#..
    ..#..........#..
    .#.....##.....#.
    .#.....##.....#.
    #..............#
    ................
    """,
    # the pediment and columns of a seat of government
    "government": """
    ................
    .....######.....
    ...##########...
    ..############..
    .####......####.
    .###..####..###.
    .###.######.###.
    .###.######.###.
    .###..####..###.
    .####......####.
    ..############..
    ...##########...
    .....######.....
    ....##....##....
    ...##......##...
    ...#........#...
    """,
    # an open book
    "research": """
    ......####......
    ......#..#......
    ......#..#......
    ......#..#......
    .....#....#.....
    .....#....#.....
    ....#......#....
    ....#......#....
    ...#........#...
    ...#..####..#...
    ..#..######..#..
    ..#.########.#..
    ..############..
    ..############..
    ...##########...
    ................
    """,
    # crossed blades
    "military": """
    .#............#.
    .##..........##.
    ..##........##..
    ...##......##...
    ....##....##....
    .....##..##.....
    ..############..
    ..############..
    .....##..##.....
    ....##....##....
    ...##......##...
    ..##........##..
    .###........###.
    .###........###.
    ..#..........#..
    ................
    """,
    # two of your people
    "people": """
    ................
    ...###....###...
    ..#####..#####..
    ..#####..#####..
    ...###....###...
    ................
    ..####....####..
    .######..######.
    ###############.
    ###############.
    ###############.
    ###############.
    ###############.
    ................
    ................
    ................
    """,
    # a scroll, rolled at both ends
    "chronicle": """
    ................
    ................
    .##############.
    .##############.
    .#............#.
    .#..########..#.
    .#............#.
    .#..########..#.
    .#............#.
    .#..######....#.
    .#............#.
    .#..########..#.
    .#............#.
    .##############.
    .##############.
    ................
    """,
    # a map, folded
    "map": """
    .......##.......
    .......##.......
    ......####......
    ......####......
    .#....####....#.
    ..##..####..##..
    ...##.####.##...
    ....########....
    .##############.
    ....########....
    ...##.####.##...
    ..##..####..##..
    .#....####....#.
    ......####......
    .......##.......
    .......##.......
    """,
}


def grid(art):
    rows = [r.strip() for r in art.strip("\n").split("\n")]
    rows = [r for r in rows if r]
    assert len(rows) == 16, f"{len(rows)} rows, want 16"
    for r in rows:
        assert len(r) == 16, f"row {r!r} is {len(r)} wide, want 16"
    return rows


def to_svg(name, art):
    """Merge each row's runs of set pixels into one rect apiece."""
    rects = []
    for y, row in enumerate(grid(art)):
        x = 0
        while x < 16:
            if row[x] == "#":
                run = 0
                while x + run < 16 and row[x + run] == "#":
                    run += 1
                rects.append(f'<rect x="{x}" y="{y}" width="{run}" height="1"/>')
                x += run
            else:
                x += 1
    return (f'<svg class="ico" viewBox="0 0 16 16" aria-hidden="true" '
            f'shape-rendering="crispEdges" fill="currentColor">{"".join(rects)}</svg>')


if __name__ == "__main__":
    svgs = {k: to_svg(k, v) for k, v in ICONS.items()}
    if "--write" not in sys.argv:
        for k, v in svgs.items():
            print(f"{k}: {len(v)} chars, {v.count('<rect')} rects")
        sys.exit(0)

    root = pathlib.Path(__file__).resolve().parent.parent
    html = (root / "index.html").read_text()
    # each bar button carries its own name, so an icon can be swapped for a name
    ids = {"buildToggle": "build", "craftToggle": "craft", "roadToggle": "roads",
           "govToggle": "government", "techToggle": "research", "milToggle": "military",
           "folkToggle": "people", "chronToggle": "chronicle", "mapToggle": "map"}
    swapped = 0
    for el_id, icon in ids.items():
        pat = re.compile(r'(<button class="btn" id="' + el_id + r'">)(<i class="ico">.*?</i>)')
        html, n = pat.subn(lambda m: m.group(1) + svgs[icon], html, count=1)
        swapped += n
    (root / "index.html").write_text(html)
    print(f"swapped {swapped} of {len(ids)} icons")
